[build]
target = "index.html"
dist = "dist"

# Add this section for static assets
[build.public_dir]
dir = "static"

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:3000/"

[serve]
address = "127.0.0.1"
port = 8080
open = true

[watch]
watch = ["src", "index.html", "static"]
