[build]
target = "index.html"
dist = "dist"

[[proxy]]
rewrite = "/api/"
backend = "https://apisimposiorevsalud.univsalud.online"

[serve]
address = "127.0.0.1"
port = 8080
open = true

[watch]
watch = ["src", "index.html", "static"]

